### ISSUE TITLE
[bug] - tensorflow/magenta-demos - AI piano doesn't work OOB (tmm2018)

### ISSUE THREAD

**Issue by tmm2018** [googlecreativelab/aiexperiments-ai-duet#21]
### [bug] - tensorflow/magenta-demos - AI piano doesn't work OOB (tmm2018)

**when trying to run ai-duet (the accompanmient thing):**
- <sub>*it compiles*</sub></sub>

---

**however, when i get to run it in macos high sierra on macbook a1278 with core i5:**
- <sub>*i open the default localhost path*</sub>
- <sub>*it doesn't display anything at all*</sub>
- <sub>*it reports some sort of error on terminal*</sub>

```
* Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET /build/Main.js HTTP/1.1" 404 -
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET /images/AIDuet_32.png HTTP/1.1" 200 -
```

**Comment by tambien** [comment]
there was an issue with the dependency and node versions. i just updated the package.json and readme to describe the exact working configuration. 

try a clean reinstall by removing node_modules and then running `npm install && npm run build` and let me know if that works for you

**Comment by ghost** [comment]
i will let you know thank you so much

**Comment by ghost** [comment]
**I still get this error message when installing via python**

```
mint:server a$ pip install -r requirements.txt
Collecting tensorflow==0.12.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/34/53/0e10581ad88bca25e5005874e46130b12efbd5eb1bda493dbf9b1648cbe2/tensorflow-0.12.1-cp27-cp27m-macosx_10_11_x86_64.whl (38.8MB)
    100% |████████████████████████████████| 38.8MB 187kB/s
Collecting magenta==0.1.8 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/4d/7c/ca73a0978e08a68fc3a333a9473bc9c142c5535d0949c79511f2224ac3f4/magenta-0.1.8-py2-none-any.whl (798kB)
    100% |████████████████████████████████| 798kB 2.5MB/s
Collecting Flask==0.12 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/0e/e9/37ee66dde483dceefe45bb5e92b387f990d4f097df40c400cf816dcebaa4/Flask-0.12-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 6.3MB/s
Collecting gunicorn==19.6.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/72/de/ec28a64885e0b390063379cca601b60b1f9e51367e0c76030ac8a5cddd5e/gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 5.9MB/s
Collecting ipython==5.1.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/17/81/edc7c7c2acf4009db35a183e5a898679fdc18c2b078d847d3e745b11faa4/ipython-5.1.0-py2-none-any.whl (747kB)
    100% |████████████████████████████████| 747kB 3.4MB/s
Requirement already satisfied: six>=1.10.0 in /Users/a/miniconda2/lib/python2.7/site-packages (from tensorflow==0.12.1->-r requirements.txt (line 1)) (1.11.0)
Collecting protobuf>=3.1.0 (from tensorflow==0.12.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/4f/56/a21f2d077ceae7fd521c0ed31fb8bb1c7f13ffbb09bf7dd27de6cf6bad08/protobuf-3.6.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 3.1MB/s
Requirement already satisfied: wheel in /Users/a/miniconda2/lib/python2.7/site-packages (from tensorflow==0.12.1->-r requirements.txt (line 1)) (0.31.1)
Collecting mock>=2.0.0 (from tensorflow==0.12.1->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow==0.12.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b6/5e/4b2c794fb57a42e285d6e0fae0e9163773c5a6a6a7e1794967fc5d2168f2/numpy-1.14.5-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 1.8MB/s
Collecting matplotlib>=1.5.3 (from magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/61/38/d70e8bf77d5cb27d5f3595edd0b3978825063feadd023786d2591e393e6e/matplotlib-2.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy>=0.18.1 (from magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pretty-midi>=0.2.6 (from magenta==0.1.8->-r requirements.txt (line 2))
Collecting Pillow>=3.4.2 (from magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/df/aa/a25f211a4686f363d8ca5a1752c43a8f42459e70af13e20713d3e636f0af/Pillow-5.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting mido>=1.1.17 (from magenta==0.1.8->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/70/37/96da8908dd6b04fec9b3d3931fa38c43d36b6942f206d9586efede105e7d/mido-1.2.8-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 71kB 8.3MB/s
Collecting click>=2.0 (from Flask==0.12->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from Flask==0.12->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from Flask==0.12->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask==0.12->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz
Collecting decorator (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in /Users/a/miniconda2/lib/python2.7/site-packages (from ipython==5.1.0->-r requirements.txt (line 5)) (39.2.0)
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting appnope; sys_platform == "darwin" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/66/a7/9f8d84f31728d78beade9b1271ccbfb290c41c1e4dc13dbd4997ad594dcd/pathlib2-2.3.2-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.3 (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/d1/b0/1a6c262da35c779dd79550137aa7c298a424987240a28792ec5ccf48f848/prompt_toolkit-1.0.15-py2-none-any.whl
Collecting pygments (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting traitlets>=4.2 (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython==5.1.0->-r requirements.txt (line 5))
Collecting pickleshare (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow==0.12.1->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow==0.12.1->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b3/5d/c196041ffdf3e34ba206db6d61d1f893a75e1f3435699ade9bd65e089a3d/pbr-4.0.4-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fa/60/b50459f291cae6bc1d0ff711b75e5130684fd3949370fdba78f6c57c1903/subprocess32-3.5.2-cp27-cp27m-macosx_10_6_intel.whl
Collecting python-dateutil>=2.1 (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pytz (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/79/d8/94633718f3f77dcb638687a77ba199325a1cb158d2d4b00c9dc17f2b5c72/kiwisolver-1.0.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=1.5.3->magenta==0.1.8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask==0.12->-r requirements.txt (line 3))
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython==5.1.0->-r requirements.txt (line 5))
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython==5.1.0->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.3->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: enum34; python_version == "2.7" in /Users/a/miniconda2/lib/python2.7/site-packages (from traitlets>=4.2->ipython==5.1.0->-r requirements.txt (line 5)) (1.1.6)
Building wheels for collected packages: itsdangerous
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /Users/a/Library/Caches/pip/wheels/2c/4a/61/5599631c1554768c6290b08c02c72d7317910374ca602ff1e5
Successfully built itsdangerous
Installing collected packages: protobuf, funcsigs, pbr, mock, numpy, tensorflow, pyparsing, backports.functools-lru-cache, subprocess32, python-dateutil, pytz, kiwisolver, cycler, matplotlib, scipy, mido, pretty-midi, Pillow, magenta, click, MarkupSafe, Jinja2, Werkzeug, itsdangerous, Flask, gunicorn, decorator, backports.shutil-get-terminal-size, appnope, scandir, pathlib2, ptyprocess, pexpect, wcwidth, prompt-toolkit, pygments, ipython-genutils, traitlets, simplegeneric, pickleshare, ipython
Successfully installed Flask-0.12 Jinja2-2.10 MarkupSafe-1.0 Pillow-5.1.0 Werkzeug-0.14.1 appnope-0.1.0 backports.functools-lru-cache-1.5 backports.shutil-get-terminal-size-1.0.0 click-6.7 cycler-0.10.0 decorator-4.3.0 funcsigs-1.0.2 gunicorn-19.6.0 ipython-5.1.0 ipython-genutils-0.2.0 itsdangerous-0.24 kiwisolver-1.0.1 magenta-0.1.8 matplotlib-2.2.2 mido-1.2.8 mock-2.0.0 numpy-1.14.5 pathlib2-2.3.2 pbr-4.0.4 pexpect-4.6.0 pickleshare-0.7.4 pretty-midi-0.2.8 prompt-toolkit-1.0.15 protobuf-3.6.0 ptyprocess-0.6.0 pygments-2.2.0 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.4 scandir-1.7 scipy-1.1.0 simplegeneric-0.8.1 subprocess32-3.5.2 tensorflow-0.12.1 traitlets-4.3.2 wcwidth-0.1.7
mint:server a$ ls
attention_rnn.mag	predict.py		server.py
basic_rnn.mag		requirements.txt
mint:server a$ python server.py
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Jun/2018 12:52:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2018 12:52:13] "GET /build/Main.js HTTP/1.1" 404 -
127.0.0.1 - - [22/Jun/2018 12:52:13] "GET /images/AIDuet_32.png HTTP/1.1" 200 -
```

**Comment by ghost** [comment]
**the repository installation is not working via python, i'm trying via node.js. that means:**
- *server version is not working*
- *static version may work.*

**let me figure out**

**Comment by ghost** [comment]
**when running npm run build (on static version), after running npm install, i am getting the following error message:**

```
mint:static a$ npm run build

> ai-duet@1.0.0 build /Users/a/Downloads/aiexperiments-ai-duet-master/static
> webpack -p

Hash: 6266680c674d8dd9793c
Version: webpack 1.15.0
Time: 29078ms
          Asset     Size  Chunks             Chunk Names
   ./build/0.js   844 kB       0  [emitted]
./build/Main.js  78.1 kB       1  [emitted]  Main
    + 422 hidden modules

WARNING in ./build/0.js from UglifyJs
Dropping unused variable frustumSize [./src/roll/Roll.js:108,8]
Side effects in initialization of unused variable aspect [./src/roll/Roll.js:109,8]
Dropping unused function scale [./src/roll/Roll.js:25,9]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/notsupported.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/notsupported.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/notsupported.css:7,0]
Condition always true [./~/three/build/three.js:2,0]
Dropping unused variable edges [./~/three/build/three.js:17399,0]
Side effects in initialization of unused variable Tutorial [./src/ai/Tutorial.js:60,13]
Side effects in initialization of unused variable About [./src/interface/About.js:33,13]
Side effects in initialization of unused variable Note [./src/keyboard/Note.js:19,13]
Side effects in initialization of unused variable RollNote [./src/roll/RollNote.js:24,13]
Condition always true [/source/AudioKeys.js:15,0]
Condition always true [./~/buckets-js/dist/buckets.min.js:2,15]
Condition always true [./~/midiconvert/build/MidiConvert.js:1,15]
Condition always true [./~/pepjs/dist/pep.js:7,0]
Condition always true [./~/startaudiocontext/StartAudioContext.js:8,0]
Dropping unreachable code [./~/startaudiocontext/StartAudioContext.js:10,3]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/about.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/about.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/about.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/glow.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/glow.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/glow.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/keyboard.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/keyboard.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/keyboard.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/tutorial.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/tutorial.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/tutorial.css:7,0]
Condition always true [./~/webmidi/webmidi.min.js:31,1632]

WARNING in ./build/Main.js from UglifyJs
Side effects in initialization of unused variable main [./src/FeatureTest.js:28,9]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/splash.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/splash.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/splash.css:7,0]
Condition always true [./~/domready/ready.js:6,0]
Dropping unreachable code [./~/domready/ready.js:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/main.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/main.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./style/main.css:7,0]
```

**after all it's still not running OOB. would appreciate this issue to be fixed**

**Comment by tambien** [comment]
reading your logs, it seems like everything installed and built ok. those messages in the terminal are all just logging info and a couple of warnings, but no errors from what i can see. 

If you've installed all the (server and static) dependencies and built the static files, which it looks you have, the next step is to run the python server by typing `python server.py` in the terminal and then open up a browser window at `http://localhost:8080/`

**Comment by ghost** [comment]
i've done that. it opens a blank window
